name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/test_release_publish.yml
    permissions:
      contents: write
    with:
      pre-release: false
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}