on:
    workflow_call:
        inputs:
            pre-release:
              required: true
              type: boolean
        secrets:
            GH_TOKEN:
              required: true
            PYPI_TOKEN:
              required: true

jobs:
    check-version:
      runs-on: ubuntu-latest
      outputs:
        should-release: ${{ steps.check.outputs.changed }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - id: check
          name: Check if .versionrc changed in this push
          run: |
            echo "Checking commits from ${{ github.event.before }} to ${{ github.sha }}"

            BASE_SHA=${{ github.event.before }}
            HEAD_SHA=${{ github.sha }}

            # Get current version
            CURRENT_VERSION=$(awk -F'"' '/^version/ {print $2}' pyproject.toml)

            # Get version from base commit
            if git show $BASE_SHA:pyproject.toml >/dev/null 2>&1; then
            BASE_VERSION=$(git show $BASE_SHA:pyproject.toml | awk -F'"' '/^version/ {print $2}')
            else
            BASE_VERSION="0.0.0"
            fi

            echo "Base version: $BASE_VERSION"
            echo "Current version: $CURRENT_VERSION"

            if  [ "$CURRENT_VERSION" != "$BASE_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "✅ version in package.json was modified in this push"

            else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "❌ version in package.json was not modified in this push"
            fi
    test:
        uses: ./.github/workflows/test.yml

    release:
        if: needs.check-version.outputs.should-release == 'true'
        needs: [check-version, test]
        permissions:
          contents: write
        uses: ./.github/workflows/tag_and_release.yml
        with:
          pre-release: ${{ inputs.pre-release }}
        secrets:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

    publish:
        needs: [check-version, release]
        if: needs.check-version.outputs.should-release == 'true'
        uses: ./.github/workflows/publish.yml
        with:
          pre-release: ${{ inputs.pre-release }}
        secrets:
            PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}